routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//САЛОНЫ
Route::get('/index.php', function(){
    return redirect('/');
});
Route::group(['prefix' => 'admin-salon', 'namespace' => 'admin_salon', 'middleware' => ['auth']], function () {
  Route::get('/', function(){
    return view('admin.index', ['company' => Resize::company()]);
  });
  //ТОВАРЫ
  Route::any('/goods', 'GoodsController@index')->name('admin-salon.goods.index');
  Route::any('/goods/hidden', 'GoodsController@index');
  Route::any('/goods/create', 'GoodsController@create')->name('admin-salon.goods.create');
  Route::any('/supplier/create', 'GoodsController@createSupplier');
  Route::any('/goods/counts/{id}', 'GoodsController@oldCount');
  Route::any('/invenory/entrance', 'GoodsController@entrance');
  Route::any('/invenory/inventory', 'GoodsController@invenory');
  Route::any('/invenory/charge', 'GoodsController@charge');
  Route::any('goods/update/description', 'GoodsController@description');
  Route::any('stroitelstvo/update/description', 'BuildingController@description');
  Route::any('proyekty/update/description', 'ProductController@description');
  Route::any('izgotovleniye/update/description', 'ManufacturingController@description');
  Route::any('bani/update/description', 'BathController@description');
  Route::any('goods/{slug}/{id}/{parametr}', 'GoodsController@update')->name('admin.goods.update.id');
  Route::any('subgoods/{slug}/{id}/{parametr}', 'GoodsController@subgoods');
  Route::any('goods/{id}/edit/', 'GoodsController@edit')->name('admin-salon.goods.edit');

  //МАТЕРИАЛЫ
  Route::any('/materials', 'MaterialsController@index')->name('admin-salon.materials.index');
  Route::any('/materials/hidden', 'MaterialsController@index');
  Route::any('/materials/create', 'MaterialsController@create')->name('admin-salon.materials.create');
  Route::any('materials/update/description', 'MaterialsController@description');
  Route::any('materials/{slug}/{id}/{parametr}', 'MaterialsController@update')->name('admin.materials.update.id');
  Route::any('submaterials/{slug}/{id}/{parametr}', 'MaterialsController@subgoods');
  Route::any('materials/{id}/edit/', 'MaterialsController@edit')->name('admin-salon.materials.edit');
  Route::any('image/materials/upload', 'MaterialsController@imageUpload');
  //УСЛУГ
  Route::any('/services', 'ServicesController@index')->name('admin-salon.services.index');
  Route::any('/services/hidden', 'ServicesController@index');
  Route::any('/services/create', 'ServicesController@create')->name('admin-salon.services.create');
  Route::any('service/{slug}/{id}/{parametr}', 'ServicesController@update');
  Route::any('services/material/delete/{id}', 'ServicesController@materialDelete');
  Route::any('services/material/counts/{id}/{params}', 'ServicesController@materialCounts');
  Route::any('services/material/{morfid}/{id}/{params}', 'ServicesController@material');
  Route::any('services/payment/{id}/{params}', 'ServicesController@payment');
  Route::any('services/option/{id}/', 'ServicesController@option');
  Route::any('services/option/{slug}/{id}/{params}', 'ServicesController@optionUpdate');
  Route::any('services/option/delete/{id}', 'ServicesController@optionDel');
  Route::any('subservices/{slug}/{id}/{parametr}', 'ServicesController@subservice');
  Route::any('services/{slug}/{id}/{parametr}', 'ServicesController@update');
  Route::any('services/{id}/edit/', 'ServicesController@edit')->name('admin-salon.services.edit');
  Route::any('service/update/description', 'ServicesController@description');

  //СОТРУДНИКИ
  Route::any('employee/', 'EmployeeController@index')->name('admin-salon.employee.index');
  Route::any('employee/store', 'EmployeeController@store')->name('admin-salon.employee.store');
  Route::any('employee/update', 'EmployeeController@update')->name('admin-salon.employee.update');

  Route::any('work/', 'WorkController@index')->name('admin-salon.work.index');
  Route::any('calendar/{slug}/{date}', 'WorkController@calendar');
  Route::any('checkday/{slug}/{date}/{month}/{user}', 'WorkController@chackday');

  Route::any('work/days/{day}/{month}/', 'WorkController@days');
  Route::any('work/{type}/{id}/', 'WorkController@service');
});







//СЕРВИС
Route::group(['prefix' => 'admin', 'namespace' => 'admin', 'middleware' => ['auth']], function () {
  Route::get('/', function(){
    $company = Resize::company();
    //dd($company);
    if($company->type == 2){
      return redirect('admin_salon/');
    }
    else{
      return view('admin.index', ['company' => Resize::company()]);
    }
  })->name('admin.index');
  Route::any('/goods/ShowDeleted', 'GoodsController@index')->name('admin.goods.ShowDeleted');
  Route::any('/bani/ShowDeleted', 'BathController@index')->name('admin.bani.ShowDeleted');
  Route::any('/izgotovleniye/ShowDeleted', 'ManufacturingController@index')->name('admin.izgotovleniye.ShowDeleted');
  Route::any('/proyekty/ShowDeleted', 'ProjectController@index')->name('admin.proyekty.ShowDeleted');
  Route::any('/service/ShowDeleted', 'ServicesController@index')->name('admin.service.ShowDeleted');
  Route::any('/stroitelstvo/ShowDeleted', 'BuildingController@index')->name('admin.stroitelstvo.ShowDeleted');
  Route::any('search/index', 'AdminController@searchIndex');
  Route::any('search/{title}', 'AdminController@search');
  //Route::any('support/view/none', 'SupportController@new')->name('admin.support.view');
  //Route::any('support/view/{id}', 'SupportController@view')->name('admin.support.view');
  Route::any('goods/images/change/all/{id}', 'GoodsController@imagesChangeAll')->name('admin.images.change.all');
    //Route::any('/support/{params}', 'SupportController@index')->name('admin.support.index');
    Route::any('/goods', 'GoodsController@index')->name('admin.product.index');
    //Route::any('/stroitelstvo', 'GoodsController@index')->name('admin.stroitelstvo.index');

    Route::any('/category/hidden', 'CategoryController@index')->name('admin.category.hidden');
    Route::any('/category/deleted', 'CategoryController@index')->name('admin.categories.ShowDeleted');
    Route::any('/goods/hidden', 'GoodsController@index')->name('admin.goods.hidden');
    Route::any('/stroitelstvo/hidden', 'buildingController@index')->name('admin.stroitelstvo.hidden');
    Route::any('/proyekty/hidden', 'ProjectController@index')->name('admin.proyekty.hidden');
    Route::any('/izgotovleniye/hidden', 'ManufacturingController@index')->name('admin.izgotovleniye.hidden');
    Route::any('/bani/hidden', 'BathController@index')->name('admin.bani.hidden');

    Route::any('/objects', 'ObjectsController@index')->name('admin.portfolio.index');
    Route::any('feedback/update/{id}', 'FeedbackController@update')->name('admin.feedback.update.new');
    Route::any('feedback/published/{id}/{param}', 'FeedbackController@published')->name('admin.feedback.published');
    Route::any('feedback/hidden', 'FeedbackController@index')->name('admin.feedback.hidden');

    Route::resource('/tape', 'TapeController', ['as' => 'admin']);
    Route::any('admin/tape/hide', 'TapeController@hide')->name('admin.tape.hide');
    Route::any('admin/tape/hidden', 'TapeController@hidden')->name('admin.tape.hidden');
    Route::any('admin/tape/imageDelete', 'TapeController@imageDelete')->name('admin.tape.imageDelete');

    Route::resource('/banner2', 'BannerxController', ['as' => 'admin']);
    Route::any('/admin/banner2/hide', 'BannerxController@hide')->name('admin.banner2.hide');
    Route::any('/admin/banner2/hidden', 'BannerxController@hidden')->name('admin.banner2.hidden');
    Route::any('/admin/banner2/imageDelete', 'BannerxController@imageDelete')->name('admin.banner2.imageDelete');

    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
    Route::resource('/contact', 'ContactController', ['as' => 'admin']);
    Route::resource('/company', 'CompanyController', ['as' => 'admin']);
    Route::resource('/work', 'WorkController', ['as' => 'admin']);
    Route::resource('/employee', 'EmployeeController', ['as' => 'admin']);
    Route::resource('/services', 'ServicesController', ['as' => 'admin']);
    Route::resource('/goods', 'GoodsController', ['as' => 'admin']);
    Route::resource('/banner', 'BannerController', ['as' => 'admin']);
    Route::resource('/opinion', 'OpinionController', ['as' => 'admin']);

    Route::resource('/information', 'InformationController', ['as' => 'admin']);
    Route::resource('/companyprice', 'CompanipriceController', ['as' => 'admin']);
    Route::resource('/menu', 'MenuController', ['as' => 'admin']);
    Route::resource('/seo', 'SeoController', ['as' => 'admin']);
    Route::resource('/include', 'IncludeController', ['as' => 'admin']);

    Route::resource('/price', 'PricelistController', ['as' => 'admin']);
    Route::resource('/jobs', 'JobsController', ['as' => 'admin']);
    Route::resource('/action', 'ActionController', ['as' => 'admin']);
    Route::resource('/news', 'NewsController', ['as' => 'admin']);
    Route::resource('/blog', 'BlogController', ['as' => 'admin']);
    Route::resource('/partners', 'PartnerController', ['as' => 'admin']);
    Route::resource('/offers', 'OfferController', ['as' => 'admin']);
    Route::resource('/subcategory', 'SubcategoryController', ['as' => 'admin']);
    Route::resource('/tizers', 'TizerController', ['as' => 'admin']);
    Route::resource('/sections', 'SectionController', ['as' => 'admin']);
    Route::resource('/orders', 'OrderController', ['as' => 'admin']);
    Route::resource('/biz', 'BizController', ['as' => 'admin']);

app/Goods.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
class Goods extends Model
{



  protected $fillable = ['published', 'main', 'slug', 'title', 'short_description', 'description', 'coast', 'type_coast', 'min_coast', 'type_min_coast', 'articuldate', 'presence', 'delivery', 'payment', 'category', 'created_by', 'modified_by', 'siteID', 'seoname', 'seotitle', 'seodescription', 'seokeywords', 'deleted', 'youtube', 'checkseo', 'sort'];


  public function setSlugAttribute($value){
    //asdsadd($this->title);
    $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40). "-". \Carbon\Carbon::now()->format('dmyHi'), '-');
  }
    public function categories(){
      return $this->hasOne('App\Category', 'id', 'category');
    }
    public function subcategory(){
      return $this->hasOne('App\Category', 'id', 'category')->with('categor');
    }
    public function images(){
      return $this->hasOne('App\Image', 'goods', 'articul')->orderBy('sort', 'asc');
    }
    public function imageses(){
      return $this->hasMany('App\Image', 'goods', 'articul')->orderBy('sort', 'asc');
    }
    public function properties(){
      return $this->belongsToMany('App\Property', 'goods_property', 'goods', 'property' );
    }

    public function CategoryGoods(){
      return $this->hasOne('App\CategoryGoods', 'goods', 'id');
    }
    public function Goods_object(){
      return $this->hasOne('App\Goods_object', 'p_g_id', 'id');
    }
    public function goods_salon(){
      return $this->hasOne('App\Goods_salon', 'parent_id', 'id');
    }
    public function service_goods(){
      return $this->hasMany('App\Service_goods', 'service', 'id')->with('products');
    }
    public function options(){
      return $this->hasMany('App\Service_option', 'service', 'id');
    }
    public function inventory(){
      return $this->hasMany('App\Inventory', 'goods', 'id');
    }
    public function type_costs(){
      return $this->hasOne('App\Type_cost', 'id', 'type_cost');
    }
    public function feedbacks(){
      return $this->hasmany('App\Feedback', 'goods', 'id');
    }
    public function doma(){
      return $this->hasOne('App\Model\Goods_doma', 'p_g_id', 'id');
    }
    // public function images(){
    //   return $this->hasOne('App\Image', 'goods', 'id')->with('imageResize');
    // }
}

resources/views/admin/goods/goods.blade.php
@forelse($product as $g)
<div class="item" id="arrayorder_{{$g->id}}">
    <div class="image">
        <img src="{{asset('storage/app')}}/{{Resize::ResizeImage($g->images, '80x80')}}" alt="">
    </div>
    <div class="info_goods">
        <div class="block">
            <div class="name"><a href=""data-toggle="modal" data-target="#exampleModalLong">{{$g->title}}</a></div>
            <div class="price">Цена: <span>{{$g->coast}}</span> руб.</div>
        </div>
        <div class="additionally">
            <div class="p_category">Раздел: <span>{{$g->categories->title or 'не выбран'}}</span></div>
            <div class="date">Добавлено: <span>{{Resize::date($g->created_at)}}</span><span> | </span> Обновлено: <span>{{Resize::date($g->updated_at)}}</span></div>
        </div>
    </div>
    <div class="status">
        <span class="sign eae @if($g->published == 1)active @endif"><a href="{{route('admin.goods.update.id', ['published',$g->id,$g->published])}}" class="link_published"></a></span>
        @if($g->published == 1 && $g->deleted == 0)<span class="sign search @if($g->checkseo == 1)active @endif"></span>@endif
        @if($g->published == 1 && $g->deleted == 0)<span class="sign star @if($g->main == 1)activeStar @endif"><a href="{{route('admin.goods.update.id', ['main',$g->id,(int)$g->main])}}"></a></span>@endif
      @if($g->published == 0 && $g->deleted == 0)<a href="{{route('admin.goods.update.id', ['deleted',$g->id,(int)$g->deleted])}}" class="link_delete"><i class="fa fa-times" aria-hidden="true"></i></a>@endif
    </div>
    @if($g->protected !== 1 || $g->protected == 1 && Auth::user()->userRolle !== 6)
    <div class="action">
        <a href="#" class="dropdown-toggle edit" data-toggle="dropdown" ></a>
        <ul class="dropdown-menu dropdown-item-edit" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
            <!-- <li><a href="{{route('admin.goods.update.id', ['published',$g->id,$g->published])}}" class="link_published">@if($g->published == 1)Скрыть @else Показать @endif</a></li> -->
            {{--<li><a href="{{route('admin.goods.destroy.goods', ['id'=>$g->id, 'deleted' => $g->deleted])}}">@if($g->deleted == 0 || $g->deleted == null)Удалить @else Восстановить @endif</a></li>--}}
            <li><a href="{{route('admin.goods.edit', [$g->id])}}?id={{$g->id}}" class="link_edit">Редактировать</a></li>
            <li><a href="{{route('admin.goods.update.id', ['main',$g->id,(int)$g->main])}}">@if($g->main == 0)На главную @else Снять с главной @endif</a></li>
        </ul>
    </div>
    @endif
</div>

@empty
@endforelse

<script type="text/javascript">
  $('.eae').click(function(){
    var link = $(this).find('a').attr('href');
    $(this).parent('.status').parent('.item').remove();
    var count_active = $('#count_active').html();
    count_active = Number.parseInt(count_active);


    var count_hidden = $('#count_hidden').html();
    count_hidden = Number.parseInt(count_hidden);
    var check = $('#link_active').hasClass('active');
    if(check == true){
      count_active = count_active-1;
      count_hidden = count_hidden+1;
    }
    else{
      count_active = count_active+1;
      count_hidden = count_hidden-1;
    }

    $('#count_active').text(count_active);
    $('#count_hidden').text(count_hidden);

    $.get(link, function(data){});

  });

  $('.link_delete').click(function(){
    var link = $(this).attr('href');
    $(this).parent('.status').parent('.item').remove();
    var count_hidden = $('#count_hidden').html();
    count_hidden = Number.parseInt(count_hidden);


    var count_deleted = $('#count_deleted').html();
    count_deleted = Number.parseInt(count_deleted);
      count_hidden = count_hidden-1;
      count_deleted = count_deleted+1;
    $('#count_hidden').text(count_hidden);
    $('#count_deleted').text(count_deleted);

    $.get(link, function(data){});
    return false;
  });

  $('.star').click(function(){
    var link = $(this).find('a').attr('href');
    var check =  $(this).hasClass('activeStar');
    if(check == true){
      $(this).removeClass('activeStar');
    }
    else{
      $(this).addClass('activeStar');
    }
    $.get(link, function(data){});

  });
</script>