routes/web.php
    Route::any('/category/deleted', 'CategoryController@index')->name('admin.categories.ShowDeleted');
    Route::any('/goods/hidden', 'GoodsController@index')->name('admin.goods.hidden');
    Route::any('/stroitelstvo/hidden', 'buildingController@index')->name('admin.stroitelstvo.hidden');
    Route::any('/proyekty/hidden', 'ProjectController@index')->name('admin.proyekty.hidden');
    Route::any('/izgotovleniye/hidden', 'ManufacturingController@index')->name('admin.izgotovleniye.hidden');
    Route::any('/bani/hidden', 'BathController@index')->name('admin.bani.hidden');

    Route::any('/objects', 'ObjectsController@index')->name('admin.portfolio.index');
    Route::any('feedback/update/{id}', 'FeedbackController@update')->name('admin.feedback.update.new');
    Route::any('feedback/published/{id}/{param}', 'FeedbackController@published')->name('admin.feedback.published');
    Route::any('feedback/hidden', 'FeedbackController@index')->name('admin.feedback.hidden');

    Route::resource('/tape', 'TapeController', ['as' => 'admin']);
    Route::any('admin/tape/hide', 'TapeController@hide')->name('admin.tape.hide');
    Route::any('admin/tape/hidden', 'TapeController@hidden')->name('admin.tape.hidden');
    Route::any('admin/tape/imageDelete', 'TapeController@imageDelete')->name('admin.tape.imageDelete');

    Route::resource('/banner2', 'BannerxController', ['as' => 'admin']);
    Route::any('/admin/banner2/hide', 'BannerxController@hide')->name('admin.banner2.hide');
    Route::any('/admin/banner2/hidden', 'BannerxController@hidden')->name('admin.banner2.hidden');
    Route::any('/admin/banner2/imageDelete', 'BannerxController@imageDelete')->name('admin.banner2.imageDelete');

    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
    Route::resource('/contact', 'ContactController', ['as' => 'admin']);
    Route::resource('/company', 'CompanyController', ['as' => 'admin']);
    Route::resource('/work', 'WorkController', ['as' => 'admin']);
    Route::resource('/employee', 'EmployeeController', ['as' => 'admin']);
    Route::resource('/services', 'ServicesController', ['as' => 'admin']);
    Route::resource('/goods', 'GoodsController', ['as' => 'admin']);
    Route::resource('/banner', 'BannerController', ['as' => 'admin']);
    Route::resource('/opinion', 'OpinionController', ['as' => 'admin']);

    Route::resource('/information', 'InformationController', ['as' => 'admin']);
    Route::resource('/companyprice', 'CompanipriceController', ['as' => 'admin']);
    Route::resource('/menu', 'MenuController', ['as' => 'admin']);
    Route::resource('/seo', 'SeoController', ['as' => 'admin']);
    Route::resource('/include', 'IncludeController', ['as' => 'admin']);

    Route::resource('/price', 'PricelistController', ['as' => 'admin']);
    Route::resource('/jobs', 'JobsController', ['as' => 'admin']);
    Route::resource('/action', 'ActionController', ['as' => 'admin']);
    Route::resource('/news', 'NewsController', ['as' => 'admin']);
    Route::resource('/blog', 'BlogController', ['as' => 'admin']);
    Route::resource('/partners', 'PartnerController', ['as' => 'admin']);
    Route::resource('/offers', 'OfferController', ['as' => 'admin']);
    Route::resource('/subcategory', 'SubcategoryController', ['as' => 'admin']);
    Route::resource('/tizers', 'TizerController', ['as' => 'admin']);
    Route::resource('/sections', 'SectionController', ['as' => 'admin']);
    Route::resource('/orders', 'OrderController', ['as' => 'admin']);
    Route::resource('/biz', 'BizController', ['as' => 'admin']);
    Route::resource('/stroitelstvo', 'BuildingController', ['as' => 'admin']);
    Route::resource('/bani', 'BathController', ['as' => 'admin']);
    Route::resource('/proyekty', 'ProjectController', ['as' => 'admin']);
    Route::resource('/izgotovleniye', 'ManufacturingController', ['as' => 'admin']);
    Route::resource('/feedback', 'FeedbackController', ['as' => 'admin']);

    Route::resource('/object', 'ObjectController', ['as' => 'admin']);
    Route::any('admin/object/hidden', 'ObjectController@hidden')->name('admin.object.hidden');
    Route::any('admin/object/hide', 'ObjectController@hide')->name('admin.object.hide');
    Route::any('object/{slug}/{id}/{parametr}', 'ObjectController@updatex')->name('admin.object.update.id');

    Route::resource('/documentation', 'DocumentController', ['as' => 'admin']);
    Route::any('documentation/{slug}/{id}/{parametr}', 'DocumentController@updatex')->name('admin.documentation.update.id');

    Route::any('order/modal', 'OrderController@modal')->name('admin.order.modal');
    Route::any('/order/create/fast', 'OrderController@create');

    Route::any('order/column/edittitle', 'OrderController@editTitleColumn');
    Route::any('order/column/create', 'OrderController@createColumn');
    Route::any('/order/column/position', 'OrderController@columnPosition')->name('order.column.position');
    Route::any('order/column/delete', 'OrderController@deleteColumn');

    Route::post('/order/modal/addcomment', 'OrderController@addComment');
    Route::any('/order/modal/editname', 'OrderController@editName');
    Route::any('/order/modal/responsible', 'OrderController@responsible');
    Route::any('/order/modal/selectcolumn', 'OrderController@selectColumn');
    Route::any('/order/modal/editperson', 'OrderController@editPerson');
    Route::any('/order/modal/editcompany', 'OrderController@editCompany');
    Route::any('/order/modal/deletetest', 'OrderController@deleteTest');
    Route::any('/order/modal/position', 'OrderController@position')->name('order.position');

    Route::any('/support', 'SupportController@index')->name('admin.support.index');
    Route::any('/support/question/{id}', 'SupportController@view');
    Route::any('/support/create', 'SupportController@create');
    Route::any('/support/store', 'SupportController@store')->name('admin.support.store');
    Route::any('/support/view/addmessage', 'SupportController@addMessage');
    Route::any('/support/view/deletequestion/{id}', 'SupportController@deleteQuestion');
    Route::post('/support/view/delete/{id}', 'SupportController@delete');

    Route::post('/information/insert', 'MenuController@insert')->name('admin.menu.insert');
    Route::post('/section/update', 'SectionController@update')->name('admin.section.update');
    Route::any('feedback/image/destroy', 'FeedbackController@imageDestroy')->name('admin.feedback.image.desctroy');
    Route::any('goods/update/description', 'GoodsController@description');
    Route::any('service/update/description', 'ServicesController@description');
    Route::any('category/update/description', 'CategoryController@description');
    Route::any('goods/update/description', 'GoodsController@description');
    Route::any('stroitelstvo/update/description', 'BuildingController@description');
    Route::any('proyekty/update/description', 'ProjectController@description');
    Route::any('izgotovleniye/update/description', 'ManufacturingController@description');
    Route::any('bani/update/description', 'BathController@description');
    //Route::any('/goods/updated/{id}/{type}/{params}', 'GoodsController@update')->name('admin.goods.updated');
    //Route::any('/services', 'GoodsController@index')->name('admin.services');
    //Route::any('/services/create', 'GoodsController@create');
    Route::post('/menu/insert', 'InformationController@insert')->name('admin.information.insert');
    Route::get('/image/company/destroy', 'CompanyController@imageDestroy')->name('admin.image.company.destroy');
    Route::get('/image/category/destroy', 'CategoryController@imageDestroy')->name('admin.image.category.destroy');
    Route::get('/image/subcategory/destroy', 'SubcategoryController@imageDestroy')->name('admin.image.subcategory.destroy');
    Route::any('image/upload', 'GoodsController@imageUpload');
    Route::any('image/category/upload', 'CategoryController@imageUpload');
    Route::any('image/category/cover/upload', 'CategoryController@coverUpload');
    Route::any('image/banner/upload', 'BannerController@imageUpload');
    Route::any('image/tizer/upload', 'TizerController@imageUpload');

    // Route::get('/master/work/choose', 'WorkController@master')->name('admin.master.work.choose');
    // Route::get('/master/work/status', 'WorkController@status')->name('admin.master.work.status');
    // Route::post('/master/work/time', 'WorkController@time')->name('admin.master.work.time');
    // Route::get('/employee/work/addServices', 'EmployeeController@addServices')->name('admin.employee.work.addServices');
    // Route::get('/employee/work/deleteServices', 'EmployeeController@deleteServices')->name('admin.employee.work.deleteServices');
    // Route::get('/services/work/addServices', 'ServicesController@addServices')->name('admin.services.work.addServices');
    // Route::get('/services/work/deleteServices', 'ServicesController@deleteServices')->name('admin.services.work.deleteServices');

    Route::get('/image/goods/destroy', 'GoodsController@imageDestroy')->name('admin.image.goods.destroy');

    Route::get('/goods/destroy/goods', 'GoodsController@destroyGoods')->name('admin.goods.destroy.goods');

    Route::get('/admin/information/edit', 'InformationController@imageDestroy')->name('admin.image.information.destroy');

    Route::post('/admin/createSite', 'AdminController@createSite')->name('admin.createSite');
    Route::post('/admin/updateSite', 'AdminController@updateSite')->name('admin.updateSite');


    Route::get('/image/employee/destroy', 'EmployeeController@imageDestroy')->name('admin.image.employee.destroy');

    Route::any('admin/git/pull', 'AdminController@gitpull')->name('admin.git.pull');
    Route::any('admin/git/push', 'AdminController@gitpush')->name('admin.git.push');


    // Route::any('admin/employee/calendar', 'EmployeeController@calendar')->name('admin.employee.calendar');

app/Http/Controllers/admin/SectionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Section;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Caching;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Auth;
use DB;
use App\Site;
use Resize;
class SectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Resize::company();
        return view('admin.sections.index',[
          'company' => $company,
          'sections' => Section::where('siteID', Auth::user()->siteID)->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function show(Section $section)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function edit(Section $section)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Section $section)
    {
      //dd($request);
      foreach ($request['published'] as $key => $value) {
        Section::where('siteID', Auth::user()->siteID)->where('id', $key)->update(['published' => $value]);
      }
      Caching::menu();
      Caching::footer();
      return redirect()->route('admin.sections.index');
        //dd($request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function destroy(Section $section)
    {
        //
    }

    public function main(){
      $i = 1;
      foreach ($_GET['arrayorder'] as $s) {
        //dd($s);
        Section::where('id', $s)->update(['main'=> $i]);
        $i++;
      }
      Caching::menu();
      Caching::footer();
    }
}

app/Http/Controllers/admin/TizerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Tizer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Cache;
use DB;
use App\Users;
use ImageResize;
use App\Site;
use Caching;
use Resize;
class TizerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

      $tizers = Tizer::where('siteID', Auth::user()->siteID)->where('status', 2)->get();
      if($request->error !== null){
        $error = $request->error;
      }
      else{
        $error = null;
      }

      //$sites = Site::get();
      //dd($company);
      //dd($company);
      $view =  '';
      if($request->ajax == null){
        $view .= view('admin.index', ['company' => Resize::company(),]);
      }
      $view .= view('admin.sections.tizers.index',[
        'siteID' => Auth::user()->siteID,
        'tizers' => $tizers,
        'error' => $error,
        'link' => $_SERVER['REQUEST_URI'],
      ]);
      return $view;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $tizers = Tizer::where('siteID', Auth::user()->siteID)->count('id');
        if($tizers >= 5){
          //dd($tizers);
          $request['ajax'] = 'true';
          $request['error'] = 1;
          return  self::index($request);
        }
        $tizer =  Tizer::where('status',1)->first();
        if($tizer == null){
          $id = Tizer::insertGetId(['status' => 1, 'siteID' => Auth::user()->siteID]);
          $tizer = Tizer::where('id',$id)->first();
        }
        $view = '';
        if($request->ajax == null){
          $view .= view('admin.index', ['company' => Resize::company(),]);
        }
          $view .= view('admin.sections.tizers.create',[
          'tizer' => $tizer,
        ]);
        return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      if($request->file('image') !== null){
        $value = $request->file('image');
        $filename  = uniqid() . '.' . $value->getClientOriginalExtension();

      ImageResize::make($value->getRealPath())->save('storage/app/public/'. $filename);
      $path = 'public/'.$filename;
      }
      else{
        $path = null;
      }
      Tizer::insert(['title' => $request->title, 'description' => $request->description,  'image' => $path, 'siteID' => Auth::user()->siteID, 'created_at' => date('Y-m-d H:i:s')]);
      return redirect()->route('admin.tizers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tizer  $tizer
     * @return \Illuminate\Http\Response
     */
    public function show(Tizer $tizer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tizer  $tizer
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,Tizer $tizer)
    {
      $tizer = Tizer::where('id', $tizer->id)->where('siteID', Auth::user()->siteID)->first();
      if($tizer == null){
        return redirect()->route('admin.tizers.index');
      }

      $view = '';
      if($request->ajax == null){
        $view .= view('admin.index', ['company' => Resize::company(),]);
      }

      $view .= view('admin.sections.tizers.create',[
        'tizer' => $tizer
      ]);
      return $view;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tizer  $tizer
     * @return \Illuminate\Http\Response
     */
    public function update($slug,$id,$parametr,Request $request, Tizer $tizer)
    {
      $update['title'] = ['title' => $parametr];
      $update['description'] = ['description' => $parametr];
      $update['status'] = ['status' => $parametr];
      // /dd($path);
        Tizer::where('id', $id)->update($update[$slug]);
        if($slug = 'status'){
          $request['ajax'] = 'true';
          return  self::index($request);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tizer  $tizer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tizer $tizer)
    {
        dd($tizer);
    }
    public function delete(Request $request)
    {
      $tizer = Tizer::where('id', $request->id)->where('siteID', Auth::user()->siteID)->first();
      if($tizer !== null){
        Storage::delete($tizer->image);
        Tizer::where('id', $request->id)->delete();
      }
      return redirect()->route('admin.tizers.index');
    }
    public function imageUpload(Request $request){
      if($request->file('file') !== null){
      $img =  $request->file('file');
        $path = Storage::putFile('public', $img);
        Tizer::where('id',$request->id)->where('siteID', Auth::user()->siteID)->update(['image' => $path]);
        $data = ['image' => $path];
      return json_encode($data);
      }

    }
}

resources/views/admin/sections/tizers/create.blade.php
        <div class="row">
            <div class="col-lg-4">
                <h2>Управление тизерами</h2>
            </div>
            <div class="col-lg-8">
                <ol class="breadcrumb">
                    <li><a href="{{route('admin.index')}}">Главная</a></li>
                    <li class="active">Тизеры</li>
                </ol>
            </div>
        </div>
        <hr>

        <div class="c_p_company">
            <div class="wide">
                <div class="box">
                    <div class="wide_title">
                        <h2>Правая штука</h2>
                    </div>
                    <div class="undefined_item">
                        {{--<div class="item">
                            <div class="name">
                                <a href=""></a>
                            </div>
                        </div>--}}
                    </div>
                </div>
            </div>
            <div class="narrow">
                <div class="box">
                    <div class="cp_edit">
                        <div class="narrow_title">
                            <h2>Редактирование тизера: <span id="edit-title">{{$tizer->title or ''}}</span></h2>
                        </div>
                        @if($tizer == null)
                        <form class="" action="{{route('admin.tizers.store')}}" method="post" enctype="multipart/form-data">
                          @else
                          <form class="" action="{{route('admin.tizers.update', $tizer)}}" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="_method" value="put">
                          @endif
                          {{ csrf_field() }}
                        <div class="perent">
                            <div class="left">
                                <label for="" class="item_name" style="line-height: 14px;padding-top: 4px;">Название:</label>
                            </div>
                            <div class="center">
                                <input type="text" name="title" class="" placeholder="Введите название тизера" maxlength="30" value="{{$tizer->title or ''}}" required="">
                            </div>
                            <div class="right">
                                <div class="help"></div>
                            </div>
                        </div>
                        <script type="text/javascript">
                        $('input[name="title"]').on('input',function(){
                          var title = $(this).val();
                          $('#edit-title').text(title);
                        });
                        $('input[name="title"]')
                        .on({
                          blur: function() {
                            $.get('/admin/tizer/title/{{$tizer->id}}/'+this.value);
                          }
                        });
                        </script>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="item_name" style="line-height: 14px;">Описание:</label>
                            </div>
                            <div class="center">
                                <textarea rows="10" name="description" maxlength="60">{{$tizer->description or ''}}</textarea>
                            </div>
                        </div>
                        <script type="text/javascript">
                        $('textarea[name="description"]')
                        .on({
                          blur: function() {
                            $.get('/admin/tizer/description/{{$tizer->id}}/'+this.value);
                          }
                        });
                        </script>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="item_name" style="line-height: 14px;">Фотографии:</label>
                            </div>
                            <div class="center">
                                <div class="file-upload">
                                    <label>
                                        <input id="sortpicture" type="file" name="sortpic" />
                                        <span>Выбрать файл</span>
                                    </label>
                                </div>
                                <input type="text" id="filename"  class="filename" disabled="" style="border: none;font-size: 12px;">
                                <div class="imgs">
                                @if($tizer !== null)
                                @if($tizer->image !==null)
                                <div class="image_group">

                                    <div class="image">
                                        <img src="{{asset('storage/app')}}/{{$tizer->image}}" alt="">

                                    </div>

                                </div>
                                @endif
                                @endif
                              </div>
                            </div>
                        </div>
                        <script type="text/javascript">
                        $('#sortpicture').on('change',function() {
                          //alert('asd');
                          var i = 1;
                          var files = $('#sortpicture').prop('files');
                          $.each(files, function (index, value) {
                            var file_data = value;
                            var form_data = new FormData();
                            form_data.append('file', file_data);
                            form_data.append('id', {{$tizer->id}});
                            $.ajax({
                                        url: '/admin/image/tizer/upload',
                                        dataType: 'text',
                                        cache: false,
                                        contentType: false,
                                        processData: false,
                                        data: form_data,
                                        type: 'post',
                                        success: function(data){
                                          data = $.parseJSON(data);
                                            $('.imgs').html('<div class="image_group" id="image'+i+'" style="width:auto;float:left;"><div class="image"><img src="{{asset('storage/app')}}/'+data.image+'" alt=""></div></div>');
                                            $('#image'+i).click(function(){
                                            });
                                        }
                             });
                             i++;
                          });

                        });

                        </script>

                        <!-- <div class="perent">
                            <div class="left">
                                <label for="" class="item_name">Видео с YouTube:</label>
                            </div>
                            <div class="center">
                                <input type="text" name="youtube" class="" placeholder="Например: http://www.youtube.com/watch?v=9X-8JiOhzX4" value="" >
                            </div>
                            <div class="right">
                                <div class="help"></div>
                            </div>
                        </div> -->
                        <div class="perent" style="margin-top: 40px;">
                            <div class="left">
                                &nbsp;
                            </div>

                            <!--

                            Кнопка сохранить и обновить меняются!

                            На странице добавления товаров - добавить
                            На странице редактировать товара - Обновить

                            -->
                            <div class="center">
                                <input type="button" class="item_button" value="Сохранить и вернутся">
                            </div>
                            <div class="right">
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
          $('.item_button').click(function(){
            $.get('/admin/tizer/status/{{$tizer->id}}/2', function(data){
              $('.admin-content').html(data);
            });
          });
        </script>
        <script>
            $(document).ready( function() {
                $(".file-upload input[type=file]").change(function(){
                    var filename = $(this).val().replace(/.*\\/, "");
                    $("#filename").val(filename);
                });
            });
        </script>