routes/web.php
    Route::any('/goods/hidden', 'GoodsController@index')->name('admin.goods.hidden');
    Route::any('/stroitelstvo/hidden', 'buildingController@index')->name('admin.stroitelstvo.hidden');
    Route::any('/proyekty/hidden', 'ProjectController@index')->name('admin.proyekty.hidden');
    Route::any('/izgotovleniye/hidden', 'ManufacturingController@index')->name('admin.izgotovleniye.hidden');
    Route::any('/bani/hidden', 'BathController@index')->name('admin.bani.hidden');

    Route::any('/objects', 'ObjectsController@index')->name('admin.portfolio.index');
    Route::any('feedback/update/{id}', 'FeedbackController@update')->name('admin.feedback.update.new');
    Route::any('feedback/published/{id}/{param}', 'FeedbackController@published')->name('admin.feedback.published');
    Route::any('feedback/hidden', 'FeedbackController@index')->name('admin.feedback.hidden');

    Route::resource('/tape', 'TapeController', ['as' => 'admin']);
    Route::any('admin/tape/hide', 'TapeController@hide')->name('admin.tape.hide');
    Route::any('admin/tape/hidden', 'TapeController@hidden')->name('admin.tape.hidden');
    Route::any('admin/tape/imageDelete', 'TapeController@imageDelete')->name('admin.tape.imageDelete');

    Route::resource('/banner2', 'BannerxController', ['as' => 'admin']);
    Route::any('/admin/banner2/hide', 'BannerxController@hide')->name('admin.banner2.hide');
    Route::any('/admin/banner2/hidden', 'BannerxController@hidden')->name('admin.banner2.hidden');
    Route::any('/admin/banner2/imageDelete', 'BannerxController@imageDelete')->name('admin.banner2.imageDelete');

    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
    Route::resource('/contact', 'ContactController', ['as' => 'admin']);
    Route::resource('/company', 'CompanyController', ['as' => 'admin']);
    Route::resource('/work', 'WorkController', ['as' => 'admin']);
    Route::resource('/employee', 'EmployeeController', ['as' => 'admin']);
    Route::resource('/services', 'ServicesController', ['as' => 'admin']);
    Route::resource('/goods', 'GoodsController', ['as' => 'admin']);
    Route::resource('/banner', 'BannerController', ['as' => 'admin']);
    Route::resource('/opinion', 'OpinionController', ['as' => 'admin']);

    Route::resource('/information', 'InformationController', ['as' => 'admin']);
    Route::resource('/companyprice', 'CompanipriceController', ['as' => 'admin']);
    Route::resource('/menu', 'MenuController', ['as' => 'admin']);
    Route::resource('/seo', 'SeoController', ['as' => 'admin']);
    Route::resource('/include', 'IncludeController', ['as' => 'admin']);

    Route::resource('/price', 'PricelistController', ['as' => 'admin']);
    Route::resource('/jobs', 'JobsController', ['as' => 'admin']);
    Route::resource('/action', 'ActionController', ['as' => 'admin']);
    Route::resource('/news', 'NewsController', ['as' => 'admin']);
    Route::resource('/blog', 'BlogController', ['as' => 'admin']);
    Route::resource('/partners', 'PartnerController', ['as' => 'admin']);
    Route::resource('/offers', 'OfferController', ['as' => 'admin']);
    Route::resource('/subcategory', 'SubcategoryController', ['as' => 'admin']);
    Route::resource('/tizers', 'TizerController', ['as' => 'admin']);
    Route::resource('/sections', 'SectionController', ['as' => 'admin']);
    Route::resource('/orders', 'OrderController', ['as' => 'admin']);
    Route::resource('/biz', 'BizController', ['as' => 'admin']);
    Route::resource('/stroitelstvo', 'BuildingController', ['as' => 'admin']);
    Route::resource('/bani', 'BathController', ['as' => 'admin']);
    Route::resource('/proyekty', 'ProjectController', ['as' => 'admin']);
    Route::resource('/izgotovleniye', 'ManufacturingController', ['as' => 'admin']);
    Route::resource('/feedback', 'FeedbackController', ['as' => 'admin']);

    Route::resource('/object', 'ObjectController', ['as' => 'admin']);
    Route::any('admin/object/hidden', 'ObjectController@hidden')->name('admin.object.hidden');
    Route::any('admin/object/hide', 'ObjectController@hide')->name('admin.object.hide');
    Route::any('object/{slug}/{id}/{parametr}', 'ObjectController@updatex')->name('admin.object.update.id');

    Route::resource('/documentation', 'DocumentController', ['as' => 'admin']);
    Route::any('documentation/{slug}/{id}/{parametr}', 'DocumentController@updatex')->name('admin.documentation.update.id');

    Route::any('order/modal', 'OrderController@modal')->name('admin.order.modal');
    Route::any('/order/create/fast', 'OrderController@create');

    Route::any('order/column/edittitle', 'OrderController@editTitleColumn');
    Route::any('order/column/create', 'OrderController@createColumn');
    Route::any('/order/column/position', 'OrderController@columnPosition')->name('order.column.position');
    Route::any('order/column/delete', 'OrderController@deleteColumn');

    Route::post('/order/modal/addcomment', 'OrderController@addComment');
    Route::any('/order/modal/editname', 'OrderController@editName');
    Route::any('/order/modal/responsible', 'OrderController@responsible');
    Route::any('/order/modal/selectcolumn', 'OrderController@selectColumn');
    Route::any('/order/modal/editperson', 'OrderController@editPerson');
    Route::any('/order/modal/editcompany', 'OrderController@editCompany');
    Route::any('/order/modal/deletetest', 'OrderController@deleteTest');
    Route::any('/order/modal/position', 'OrderController@position')->name('order.position');

    Route::any('/support', 'SupportController@index')->name('admin.support.index');
    Route::any('/support/question/{id}', 'SupportController@view');
    Route::any('/support/create', 'SupportController@create');
    Route::any('/support/store', 'SupportController@store')->name('admin.support.store');
    Route::any('/support/view/addmessage', 'SupportController@addMessage');
    Route::any('/support/view/deletequestion/{id}', 'SupportController@deleteQuestion');
    Route::post('/support/view/delete/{id}', 'SupportController@delete');

    Route::post('/information/insert', 'MenuController@insert')->name('admin.menu.insert');
    Route::post('/section/update', 'SectionController@update')->name('admin.section.update');
    Route::any('feedback/image/destroy', 'FeedbackController@imageDestroy')->name('admin.feedback.image.desctroy');
    Route::any('goods/update/description', 'GoodsController@description');
    Route::any('service/update/description', 'ServicesController@description');
    Route::any('category/update/description', 'CategoryController@description');
    Route::any('goods/update/description', 'GoodsController@description');
    Route::any('stroitelstvo/update/description', 'BuildingController@description');
    Route::any('proyekty/update/description', 'ProjectController@description');
    Route::any('izgotovleniye/update/description', 'ManufacturingController@description');
    Route::any('bani/update/description', 'BathController@description');
    //Route::any('/goods/updated/{id}/{type}/{params}', 'GoodsController@update')->name('admin.goods.updated');
    //Route::any('/services', 'GoodsController@index')->name('admin.services');
    //Route::any('/services/create', 'GoodsController@create');
    Route::post('/menu/insert', 'InformationController@insert')->name('admin.information.insert');
    Route::get('/image/company/destroy', 'CompanyController@imageDestroy')->name('admin.image.company.destroy');
    Route::get('/image/category/destroy', 'CategoryController@imageDestroy')->name('admin.image.category.destroy');
    Route::get('/image/subcategory/destroy', 'SubcategoryController@imageDestroy')->name('admin.image.subcategory.destroy');
    Route::any('image/upload', 'GoodsController@imageUpload');
    Route::any('image/category/upload', 'CategoryController@imageUpload');
    Route::any('image/category/cover/upload', 'CategoryController@coverUpload');
    Route::any('image/banner/upload', 'BannerController@imageUpload');
    Route::any('image/tizer/upload', 'TizerController@imageUpload');

    // Route::get('/master/work/choose', 'WorkController@master')->name('admin.master.work.choose');
    // Route::get('/master/work/status', 'WorkController@status')->name('admin.master.work.status');
    // Route::post('/master/work/time', 'WorkController@time')->name('admin.master.work.time');
    // Route::get('/employee/work/addServices', 'EmployeeController@addServices')->name('admin.employee.work.addServices');
    // Route::get('/employee/work/deleteServices', 'EmployeeController@deleteServices')->name('admin.employee.work.deleteServices');
    // Route::get('/services/work/addServices', 'ServicesController@addServices')->name('admin.services.work.addServices');
    // Route::get('/services/work/deleteServices', 'ServicesController@deleteServices')->name('admin.services.work.deleteServices');

    Route::get('/image/goods/destroy', 'GoodsController@imageDestroy')->name('admin.image.goods.destroy');

    Route::get('/goods/destroy/goods', 'GoodsController@destroyGoods')->name('admin.goods.destroy.goods');

    Route::get('/admin/information/edit', 'InformationController@imageDestroy')->name('admin.image.information.destroy');

    Route::post('/admin/createSite', 'AdminController@createSite')->name('admin.createSite');
    Route::post('/admin/updateSite', 'AdminController@updateSite')->name('admin.updateSite');


    Route::get('/image/employee/destroy', 'EmployeeController@imageDestroy')->name('admin.image.employee.destroy');

    Route::any('admin/git/pull', 'AdminController@gitpull')->name('admin.git.pull');
    Route::any('admin/git/push', 'AdminController@gitpush')->name('admin.git.push');


    // Route::any('admin/employee/calendar', 'EmployeeController@calendar')->name('admin.employee.calendar');

app/Section.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
    //
    public function category(){
        return $this->hasMany('App\Category', 'type', 'type')->where('published', 1)->limit(10);
    }
    public function texts(){
        return $this->hasOne('App\Text', 'id', 'setting')->with('images');;
    }
}

app/Http/Controllers/admin/SectionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Section;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Caching;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Auth;
use DB;
use App\Site;
use Resize;
class SectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Resize::company();
        return view('admin.sections.index',[
          'company' => $company,
          'sections' => Section::where('siteID', Auth::user()->siteID)->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function show(Section $section)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function edit(Section $section)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Section $section)
    {
      //dd($request);
      foreach ($request['published'] as $key => $value) {
        Section::where('siteID', Auth::user()->siteID)->where('id', $key)->update(['published' => $value]);
      }
      Caching::menu();
      Caching::footer();
      return redirect()->route('admin.sections.index');
        //dd($request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function destroy(Section $section)
    {
        //
    }

    public function main(){
      $i = 1;
      foreach ($_GET['arrayorder'] as $s) {
        //dd($s);
        Section::where('id', $s)->update(['main'=> $i]);
        $i++;
      }
      Caching::menu();
      Caching::footer();
    }
}

resources/views/admin/sections/reviews/edit.blade.php
@include('admin.index')

    <div class="row">
        <div class="col-lg-4">
            <h2>Управление компанией</h2>
        </div>
        <div class="col-lg-8">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li class="active">Отзывы</li>
            </ol>
        </div>
    </div>
    <hr>

    <div class="c_p_company">
        <div class="wide">
            <div class="box">

            </div>
        </div>
        <div class="narrow">
            <div class="box">
                <div class="cp_edit">
                    <div class="narrow_title">
                      @if($feedback == null)
                        <h2>Добавление отзыва</h2>
                      @else
                      <h2>Редактирование отзыва</h2>
                      @endif
                    </div>
                    @if($feedback == null)
                    <form action="{{route('admin.feedback.store')}}" method="post" enctype="multipart/form-data">
                    @else
                    <form action="{{route('admin.feedback.update.new', [$feedback])}}" method="post" enctype="multipart/form-data">
                    @endif
                    {{csrf_field()}}
                    <div class="perent">
                        <div class="left">
                            <label for="" class="item_name" style="line-height: 14px;padding-top: 4px;">Название:</label>
                        </div>
                        <div class="center">
                            <input type="text" name="name" class="" placeholder="ФИО автора" value="{{$feedback->name or ''}}" required="">
                        </div>
                        <div class="right">
                            <div class="help"></div>
                        </div>
                    </div>
                    <div class="perent">
                        <div class="left">
                            <label for="" class="item_name" style="line-height: 14px;">Фотография автора:</label>
                        </div>
                        <div class="center">
                            <div class="file-upload">
                                <label>
                                    <input type="file" name="ava">
                                    <span>Выбрать файл</span>
                                </label>
                            </div>
                            <input type="text" id="filename" class="filename"  disabled="" style="border: none;font-size: 12px;">
                            @if($feedback !== null && $feedback->image !== null)
                            <div class="image_group ava">
                                <div class="image">
                                    <img src="/storage/app/{{$feedback->image or ''}}" alt="">
                                    <a class="delete" id="del"></a>
                                </div>
                            </div>

                            <script type="text/javascript">
                              $('#del').click(function(){
                                $('.ava').remove();
                                $.get('{{route('admin.feedback.image.desctroy', ['id' => $feedback->id])}}', function(data){});
                              });
                            </script>
                            @endif
                        </div>
                    </div>
                    <div class="perent">
                        <div class="left">
                            <label for="" class="item_name" style="line-height: 14px;">Описание:</label>
                        </div>
                        <div class="center">
                            <textarea rows="10" name="text">{{$feedback->description or ''}}</textarea>
                        </div>
                    </div>
                    <script>
                        CKEDITOR.replace('text');
                    </script>
                    <div class="perent">
                        <div class="left">
                            <label for="" class="item_name" style="line-height: 14px;">Фотографии:</label>
                        </div>
                        <div class="center">
                            <div class="file-upload">
                                <label>
                                    <input type="file" name="files[]" multiple>
                                    <span>Выбрать файл</span>
                                </label>
                            </div>
                            <input type="text" id="filename" class="filename" disabled="" style="border: none;font-size: 12px;">

                            @if($feedback !== null)
                            @forelse($feedback->images as $image)
                            <div class="image_group" id="image{{$image->id}}" style="width:auto; float:left;">

                                <div class="image">
                                    <img src="{{asset('storage/app')}}/{{$image->images}}" alt="">
                                    <a  class="delete" id="send{{$image->id}}"></a>
                                </div>

                            </div>
                            <script type="text/javascript">
                              $('#send{{$image->id}}').click(function(){
                                $('#image{{$image->id}}').remove();
                                $.get('{{route('admin.image.goods.destroy', ['id' => $image->id])}}', function(data){});
                              });
                            </script>
                            @empty
                            @endforelse
                            <div class="clearfix"></div>
                            @endif
                        </div>
                    </div>
                    <div class="perent" style="margin-top: 40px;">
                        <div class="left">
                            &nbsp;
                        </div>

                        <!--

                        Кнопка сохранить и обновить меняются!

                        На странице добавления товаров - добавить
                        На странице редактировать товара - Обновить

                        -->

                        <div class="center">
                            <input type="submit" class="item_button" value="обновить">
                        </div>
                        <div class="right">
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready( function() {
            $(".file-upload input[type=file]").change(function(){
                var filename = $(this).val().replace(/.*\\/, "");
                $("#filename").val(filename);
            });
        });
    </script>


</div>


</html>

resources/views/admin/sections/reviews/index.blade.php
@include('admin.index')
    <div class="row">
        <div class="col-lg-4">
            <h2>Управление сайтами</h2>
        </div>
        <div class="col-lg-8">
            <ol class="breadcrumb">
                <li><a href="">Главная</a></li>
                <li class="active">Отзывы</li>
            </ol>
        </div>
    </div>
    <hr>

    <div class="c_p_company">
        <div class="wide">
            <div class="box">
                <div class="help">
                    <div class="title">
                        <h2>Правая штука</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="narrow">
            <div class="box">
                <style>
                    .reviews h2{font-size:16px;font-weight:600;margin:0}
                    .reviews .item{width:100%;position:relative;padding:10px;border-bottom:1px solid #ddd;display:inline-flex}
                    .reviews .item:hover{background-color:#f7f7f7}
                    .reviews .item .image{background:#ddd;min-width:45px;width:45px;height:45px;margin-right:15px}
                    .reviews .item img{width:45px;height:45px;object-fit:cover}
                    .reviews .item .info{width:70%;padding-right:30px;position:relative}
                    .reviews .info .name{font-size:14px;line-height:16px;font-weight:600;color:#333;margin-bottom:10px}
                    .reviews .gallery{display:table;width:100%;margin-top:10px}
                    .reviews .gallery .image{width:75px;height:50px;margin-right:5px;margin-bottom:5px;float:left}
                    .reviews .gallery img{width:100%;height:100%;object-fit:cover}
                    .rating{color:#fdcc63;font-size:12px;line-height:12px;margin-bottom:6px}
                    .reviews .info .desc{color:#444;margin-top:5px;font-size:15px;line-height:20px;max-height:85px;position:relative;overflow:hidden}
                    .reviews .info .desc p:last-child{margin:0}
                    .reviews .info .toggle-btn{color:#007bff;font-size:15px;line-height:17px;margin-top:5px;display:table}
                    .reviews .info .text-open{overflow:visible;height:auto}
                    .reviews .info .text-open + .toggle-btn{display:none}
                    .reviews .status{font-size:14px;width:15%}
                    .reviews .status .sign{margin-right:5px}
                    .reviews .status .none{color:#e62e04}
                    .reviews .status .active{color:#5cb85c}
                    .reviews .star:before{font-family:FontAwesome;color:#fec107;content:"\f005"}
                    .reviews .search:before{font-family:FontAwesome;content:"\f002"}
                    .reviews .trash:before{font-family:FontAwesome;color:#e62e04;content:"\f014"}
                    .reviews .status .eae:before{font-family:FontAwesome;content:"\f06e"}
                    .reviews .iclose:before{font-family:FontAwesome;content:"\f00d"}
                    .reviews .action{text-align:right;width:10%}
                    .reviews .action .edit:before{font-family:FontAwesome;color:#666;content:"\f141"}
                    .reviews .button-edit{cursor:pointer;z-index:3;width:102px;height:30px;padding:7px 14px;margin-left:25px;font-size:14px;background:#0095eb;color:#fff;border-radius:5px;text-align:center;vertical-align:-webkit-baseline-middle}
                </style>
                <div class="reviews">
                    <div class="narrow_title">
                        <div class="left">
                            <h2>Отзывы</h2>
                        </div>
                        <div class="right">
                            <span class="button-edit"><a href="{{route('admin.feedback.create')}}">Добавить</a></span>
                        </div>
                    </div>
                    <div class="sort">
                      <div class="page_cat">
                          <span><a href="{{route('admin.feedback.index')}}"  id="link_active">Активные <span id="count_active">{{$countActive or ''}}</span></a></span>
                          <span> | </span>
                          <span><a href="{{route('admin.feedback.hidden')}}"  id="link_hidden">Скрытые <span id="count_hidden">{{$countHide or ''}}</span></a></span>
                          {{--<span> | </span>
                          <span><a href="{{route('admin.goods.ShowDeleted')}}">Удаленные {{$countDeleted or ''}}</a></span>--}}
                      </div>
                    </div>
                    @forelse($feedbacks as $feedback)
                    <div class="item">
                        <div class="image">
                            <a href=""><img src="/storage/app/{{$feedback->image}}" alt=""></a>
                        </div>
                        <div class="info">
                            <div class="block">
                                <div class="name">{{$feedback->name or ''}}</div>
                            </div>
                            <div class="rating"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
                            <div class="desc">
                              {!! $feedback->description or '' !!}
                            </div>
                            <a href="" class="toggle-btn">Читать полностью</a>
                            <div class="gallery tz-gallery">
                                @forelse($feedback->images as $image)
                                <div class="image">
                                    <a href="/storage/app/{{$image->images or ''}}" class="lightbox">
                                        <img src="/storage/app/{{$image->images or ''}}" alt="">
                                    </a>
                                </div>
                                @empty
                                @endforelse
                            </div>
                        </div>
                        <div class="status">
                            <span class="sign eae @if($feedback->published == 1) active @endif"><a href="{{route('admin.feedback.published', [$feedback->id,$feedback->published])}}" class="link_published"></a></span>
                        </div>
                        <div class="action">
                            <a href="#" class="dropdown-toggle edit" data-toggle="dropdown"></a>
                            <ul class="dropdown-menu dropdown-item-edit" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
                                <li><a href="{{route('admin.feedback.edit', [$feedback])}}">Редактировать</a></li>
                            </ul>
                        </div>
                    </div>
                    @empty
                    @endforelse
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(".toggle-btn").click(function(e) {
        e.preventDefault();
        $(this).prev().toggleClass("text-open")
    })
</script>
<script type="text/javascript">
  $('.eae').click(function(){
    var link = $(this).find('a').attr('href');
    $(this).parent('.status').parent('.item').remove();
    var count_active = $('#count_active').html();
    count_active = Number.parseInt(count_active);


    var count_hidden = $('#count_hidden').html();
    count_hidden = Number.parseInt(count_hidden);
    var check = $('#link_active').hasClass('active');
    if(check == true){
      count_active = count_active-1;
      count_hidden = count_hidden+1;
    }
    else{
      count_active = count_active+1;
      count_hidden = count_hidden-1;
    }

    $('#count_active').text(count_active);
    $('#count_hidden').text(count_hidden);

    $.get(link, function(data){});

  });

</script>
<link rel="stylesheet" href="https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>baguetteBox.run('.tz-gallery');</script>

</html>