routes/web.php
  Route::any('service/{slug}/{id}/{parametr}', 'ServicesController@update');
  Route::any('services/material/delete/{id}', 'ServicesController@materialDelete');
  Route::any('services/material/counts/{id}/{params}', 'ServicesController@materialCounts');
  Route::any('services/material/{morfid}/{id}/{params}', 'ServicesController@material');
  Route::any('services/payment/{id}/{params}', 'ServicesController@payment');
  Route::any('services/option/{id}/', 'ServicesController@option');
  Route::any('services/option/{slug}/{id}/{params}', 'ServicesController@optionUpdate');
  Route::any('services/option/delete/{id}', 'ServicesController@optionDel');
  Route::any('subservices/{slug}/{id}/{parametr}', 'ServicesController@subservice');
  Route::any('services/{slug}/{id}/{parametr}', 'ServicesController@update');
  Route::any('services/{id}/edit/', 'ServicesController@edit')->name('admin-salon.services.edit');
  Route::any('service/update/description', 'ServicesController@description');

  //СОТРУДНИКИ
  Route::any('employee/', 'EmployeeController@index')->name('admin-salon.employee.index');
  Route::any('employee/store', 'EmployeeController@store')->name('admin-salon.employee.store');
  Route::any('employee/update', 'EmployeeController@update')->name('admin-salon.employee.update');

  Route::any('work/', 'WorkController@index')->name('admin-salon.work.index');
  Route::any('calendar/{slug}/{date}', 'WorkController@calendar');
  Route::any('checkday/{slug}/{date}/{month}/{user}', 'WorkController@chackday');

  Route::any('work/days/{day}/{month}/', 'WorkController@days');
  Route::any('work/{type}/{id}/', 'WorkController@service');
});







//СЕРВИС
Route::group(['prefix' => 'admin', 'namespace' => 'admin', 'middleware' => ['auth']], function () {
  Route::get('/', function(){
    $company = Resize::company();
    //dd($company);
    if($company->type == 2){
      return redirect('admin_salon/');
    }
    else{
      return view('admin.index', ['company' => Resize::company()]);
    }
  })->name('admin.index');
  Route::any('/goods/ShowDeleted', 'GoodsController@index')->name('admin.goods.ShowDeleted');
  Route::any('/bani/ShowDeleted', 'BathController@index')->name('admin.bani.ShowDeleted');
  Route::any('/izgotovleniye/ShowDeleted', 'ManufacturingController@index')->name('admin.izgotovleniye.ShowDeleted');
  Route::any('/proyekty/ShowDeleted', 'ProjectController@index')->name('admin.proyekty.ShowDeleted');
  Route::any('/service/ShowDeleted', 'ServicesController@index')->name('admin.service.ShowDeleted');
  Route::any('/stroitelstvo/ShowDeleted', 'BuildingController@index')->name('admin.stroitelstvo.ShowDeleted');
  Route::any('search/index', 'AdminController@searchIndex');
  Route::any('search/{title}', 'AdminController@search');
  //Route::any('support/view/none', 'SupportController@new')->name('admin.support.view');
  //Route::any('support/view/{id}', 'SupportController@view')->name('admin.support.view');
  Route::any('goods/images/change/all/{id}', 'GoodsController@imagesChangeAll')->name('admin.images.change.all');
    //Route::any('/support/{params}', 'SupportController@index')->name('admin.support.index');
    Route::any('/goods', 'GoodsController@index')->name('admin.product.index');
    //Route::any('/stroitelstvo', 'GoodsController@index')->name('admin.stroitelstvo.index');

    Route::any('/category/hidden', 'CategoryController@index')->name('admin.category.hidden');
    Route::any('/category/deleted', 'CategoryController@index')->name('admin.categories.ShowDeleted');
    Route::any('/goods/hidden', 'GoodsController@index')->name('admin.goods.hidden');
    Route::any('/stroitelstvo/hidden', 'buildingController@index')->name('admin.stroitelstvo.hidden');
    Route::any('/proyekty/hidden', 'ProjectController@index')->name('admin.proyekty.hidden');
    Route::any('/izgotovleniye/hidden', 'ManufacturingController@index')->name('admin.izgotovleniye.hidden');
    Route::any('/bani/hidden', 'BathController@index')->name('admin.bani.hidden');

    Route::any('/objects', 'ObjectsController@index')->name('admin.portfolio.index');
    Route::any('feedback/update/{id}', 'FeedbackController@update')->name('admin.feedback.update.new');
    Route::any('feedback/published/{id}/{param}', 'FeedbackController@published')->name('admin.feedback.published');
    Route::any('feedback/hidden', 'FeedbackController@index')->name('admin.feedback.hidden');

    Route::resource('/tape', 'TapeController', ['as' => 'admin']);
    Route::any('admin/tape/hide', 'TapeController@hide')->name('admin.tape.hide');
    Route::any('admin/tape/hidden', 'TapeController@hidden')->name('admin.tape.hidden');
    Route::any('admin/tape/imageDelete', 'TapeController@imageDelete')->name('admin.tape.imageDelete');

    Route::resource('/banner2', 'BannerxController', ['as' => 'admin']);
    Route::any('/admin/banner2/hide', 'BannerxController@hide')->name('admin.banner2.hide');
    Route::any('/admin/banner2/hidden', 'BannerxController@hidden')->name('admin.banner2.hidden');
    Route::any('/admin/banner2/imageDelete', 'BannerxController@imageDelete')->name('admin.banner2.imageDelete');

    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
    Route::resource('/contact', 'ContactController', ['as' => 'admin']);
    Route::resource('/company', 'CompanyController', ['as' => 'admin']);
    Route::resource('/work', 'WorkController', ['as' => 'admin']);
    Route::resource('/employee', 'EmployeeController', ['as' => 'admin']);
    Route::resource('/services', 'ServicesController', ['as' => 'admin']);
    Route::resource('/goods', 'GoodsController', ['as' => 'admin']);
    Route::resource('/banner', 'BannerController', ['as' => 'admin']);
    Route::resource('/opinion', 'OpinionController', ['as' => 'admin']);

    Route::resource('/information', 'InformationController', ['as' => 'admin']);
    Route::resource('/companyprice', 'CompanipriceController', ['as' => 'admin']);
    Route::resource('/menu', 'MenuController', ['as' => 'admin']);
    Route::resource('/seo', 'SeoController', ['as' => 'admin']);
    Route::resource('/include', 'IncludeController', ['as' => 'admin']);

    Route::resource('/price', 'PricelistController', ['as' => 'admin']);
    Route::resource('/jobs', 'JobsController', ['as' => 'admin']);
    Route::resource('/action', 'ActionController', ['as' => 'admin']);
    Route::resource('/news', 'NewsController', ['as' => 'admin']);
    Route::resource('/blog', 'BlogController', ['as' => 'admin']);
    Route::resource('/partners', 'PartnerController', ['as' => 'admin']);
    Route::resource('/offers', 'OfferController', ['as' => 'admin']);
    Route::resource('/subcategory', 'SubcategoryController', ['as' => 'admin']);
    Route::resource('/tizers', 'TizerController', ['as' => 'admin']);
    Route::resource('/sections', 'SectionController', ['as' => 'admin']);
    Route::resource('/orders', 'OrderController', ['as' => 'admin']);
    Route::resource('/biz', 'BizController', ['as' => 'admin']);
    Route::resource('/stroitelstvo', 'BuildingController', ['as' => 'admin']);
    Route::resource('/bani', 'BathController', ['as' => 'admin']);
    Route::resource('/proyekty', 'ProjectController', ['as' => 'admin']);
    Route::resource('/izgotovleniye', 'ManufacturingController', ['as' => 'admin']);
    Route::resource('/feedback', 'FeedbackController', ['as' => 'admin']);

    Route::resource('/object', 'ObjectController', ['as' => 'admin']);
    Route::any('admin/object/hidden', 'ObjectController@hidden')->name('admin.object.hidden');
    Route::any('admin/object/hide', 'ObjectController@hide')->name('admin.object.hide');
    Route::any('object/{slug}/{id}/{parametr}', 'ObjectController@updatex')->name('admin.object.update.id');

    Route::resource('/documentation', 'DocumentController', ['as' => 'admin']);
    Route::any('documentation/{slug}/{id}/{parametr}', 'DocumentController@updatex')->name('admin.documentation.update.id');

    Route::any('order/modal', 'OrderController@modal')->name('admin.order.modal');
    Route::any('/order/create/fast', 'OrderController@create');

    Route::any('order/column/edittitle', 'OrderController@editTitleColumn');
    Route::any('order/column/create', 'OrderController@createColumn');
    Route::any('/order/column/position', 'OrderController@columnPosition')->name('order.column.position');
    Route::any('order/column/delete', 'OrderController@deleteColumn');

    Route::post('/order/modal/addcomment', 'OrderController@addComment');
    Route::any('/order/modal/editname', 'OrderController@editName');
    Route::any('/order/modal/responsible', 'OrderController@responsible');
    Route::any('/order/modal/selectcolumn', 'OrderController@selectColumn');
    Route::any('/order/modal/editperson', 'OrderController@editPerson');
    Route::any('/order/modal/editcompany', 'OrderController@editCompany');
    Route::any('/order/modal/deletetest', 'OrderController@deleteTest');
    Route::any('/order/modal/position', 'OrderController@position')->name('order.position');

    Route::any('/support', 'SupportController@index')->name('admin.support.index');
    Route::any('/support/question/{id}', 'SupportController@view');
    Route::any('/support/create', 'SupportController@create');
    Route::any('/support/store', 'SupportController@store')->name('admin.support.store');
    Route::any('/support/view/addmessage', 'SupportController@addMessage');
    Route::any('/support/view/deletequestion/{id}', 'SupportController@deleteQuestion');
    Route::post('/support/view/delete/{id}', 'SupportController@delete');

    Route::post('/information/insert', 'MenuController@insert')->name('admin.menu.insert');
    Route::post('/section/update', 'SectionController@update')->name('admin.section.update');
    Route::any('feedback/image/destroy', 'FeedbackController@imageDestroy')->name('admin.feedback.image.desctroy');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Str;
class Category extends Model
{
    protected $fillable = ['title', 'type', 'slug', 'main', 'parent_id', 'published', 'created_by', 'siteID', 'modified_by', 'seoname', 'seotitle', 'seodescription', 'seokeywords', 'description', 'youtube', 'deleted', 'checkseo', 'sort', 'offer'];

    public function setSlugAttribute($value){
      //dd($this->title);
      $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40). "-". \Carbon\Carbon::now()->format('dmyHi'), '-');
    }

    public function children(){

      return $this->hasMany(self::class, 'parent_id');
    }

    public function images(){
      return $this->hasOne('App\Image', 'category', 'articul');
    }
    public function imageses(){
      return $this->hasMany('App\Image', 'category', 'articul');
    }
    public function goods(){
      return $this->hasMany('App\Goods', 'category', 'id')->with('Goods_object')->with('images')->where('published', 1);
    }

    public function services(){
      return $this->hasMany('App\Goods', 'category', 'id')->with('Goods_object')->where('published', 1);
    }
    public function subcategories(){
      return $this->hasMany('App\Category', 'parent_id', 'id')->where('published',1)->with('goods')->with('services')->with('images')->orderBy('sort', 'asc');
    }
    public function subcategoriesAll(){
      return $this->hasMany('App\Category', 'parent_id', 'id')->with('goods')->with('images')->orderby('sort', 'asc');
    }
    public function categor(){
      return $this->hasOne('App\Category', 'id', 'parent_id')->with('section');
    }
    public function objects(){
         return $this->hasMany('App\Objects', 'parent_id', 'id');
    }
    public function goodsAll(){
       return $this->hasMany('App\Goods', 'category', 'id')->with('imageses');
    }
    public function section(){

      return $this->hasOne('App\Section', 'type', 'type');
    }
    // public function images(){
    //   return $this->hasMany('App\Image', 'company', 'id')->with('imageResize');
    // }
}

resources/views/admin/categories/subcategories.blade.php
<?php //dd($categories); ?>
@forelse($categories as $subcategory)
<?php //dd($subcategory); ?>
<div class="item" id="arrayorder_{{$subcategory->id}}">
    <div class="image">
        <a href=""><img src="{{asset('storage/app')}}/{{$subcategory->images->images or '/public/none-img.png'}}" alt=""></a>
    </div>
    <div class="info">
        <div class="block">
            <div class="name"><a href="">{{$subcategory->title}}</a></div>
        </div>
        <div class="additionally">
            <div class="type">Раздел: <span>@if($subcategory->type == 0)Услуги @else Товары @endif</span></div>
            <div class="quantity">Количество товаров в категории: <span><a href="/admin/subcategory/goods/{{$subcategory->id}}">{{count($subcategory->goods)}}</a></span> шт.</div>
        </div>
    </div>
    <div class="status">
        <span class="sign eae @if($subcategory->published ==1)active @endif"></span>
        @if($subcategory->checkseo == 1)
        <span class="sign search @if($subcategory->published == 1) active @endif"></span>
        @endif
        <span class="sign @if($subcategory->main == 1)star @endif"></span>
    </div>
    <div class="action">
        <a href="#" class="dropdown-toggle edit" data-toggle="dropdown"></a>
        <ul class="dropdown-menu dropdown-item-edit" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
            <li><a href="{{route('admin.category.hide')}}?id={{$subcategory->id}}">@if($subcategory->published == 1)Скрыть @else Показать @endif</a></li>
            <li><a href="{{route('admin.category.edit', [$subcategory->id])}}">Редактировать</a></li>
            @if($subcategory->main == 1)
            <li><a href="{{route('admin.category.main', ['id'=>$subcategory->id])}}">Снять с главной</a></li>
            @else
            <li><a href="{{route('admin.category.main', ['id'=>$subcategory->id])}}">На главную</a></li>
            @endif
        </ul>
    </div>
</div>

@empty
@endforelse

resources/views/admin/categories/subcategoryCreate.blade.php
@include('admin.admin.include.mainHeader')
<div class="admin">
@include('admin.admin.include.header')
@include('admin.admin.include.lmenu')

    <div class="admin-content">
      <div class="row">
          <div class="col-lg-4">
              <h2>Управление категориями</h2>
          </div>
          <div class="col-lg-8">
              <ol class="breadcrumb">
                  <li><a href="">Главная</a></li>
                  <li class="active">Категории</li>
              </ol>
          </div>
      </div>
      <hr>

        <div class="c_p_company">
            <div class="wide">
                <div class="box">
                    <div class="wide_title">
                        <h2>Правая штука</h2>
                    </div>
                    <div class="undefined_item">
                      {{--<div class="item">
                          <div class="name">
                              <a href=""></a>
                          </div>
                      </div>--}}
                  </div>
              </div>
          </div>
            <div class="narrow">
                <div class="box">
                    <div class="cp_edit">
                      @if($subcategory !== null)
                      <?php //dd($subcategory); ?>
                      <form class="form-horizontal" action="{{route('admin.subcategory.update', $subcategory->id)}}" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_method" value="put">
                    <input type="hidden" name="subcategory" value="{{$subcategory->id}}">
                    @else
                      <form action="{{route('admin.subcategory.store')}}" method="post" enctype="multipart/form-data">
                        @endif
                        {{ csrf_field() }}
                        <div class="narrow_title">
                            @if($subcategory == null)
                                <h2>Добавление категории</h2>
                            @else
                                <h2>Редактирование категории: {{$subcategory->title or ''}}</h2>
                            @endif
                        </div>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="name_item">Выберите категорию:</label>
                            </div>
                            <div class="center">
                              <select class="form-control" name="subcategory" required>
                                  @forelse($categories as $c)
                                  @if($subcategory !== null && count($subcategory->categor)>0)
                                  <option value="{{$c->id}}" @if($c->id == $subcategory->categor->id)selected="" @endif>{{$c->title}}</option>
                                  @else
                                  <option value="{{$c->id}}">{{$c->title}}</option>
                                  @endif
                                  @empty

                                  @endforelse
                              </select>
                            </div>
                        </div>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="seo_name">SEO</label>
                            </div>
                            <div class="center">
                                <label class="switch">
                                    <input type="checkbox" id="watch" name="checkseo" value="1" @if($subcategory !== null) @if($subcategory->checkseo == 1)checked @endif @endif>
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                        <div class="seo_group" id="switch_seo" style="display:none">
                            <div class="item_line">
                                <div class="left">
                                    <label for="" class="item_name" style="padding-top: 4px">Название на странице категории:</label>
                                </div>
                                <div class="center">
                                    <input type="text" name="seoname" class="" placeholder="Название на странице категории" value="{{$subcategory->seoname or ''}}">
                                </div>
                                <div class="right">
                                    <div class="help"></div>
                                </div>
                            </div>
                            <div class="item_line">
                                <div class="left">
                                    <label for="" class="item_name">Мета-тег Title:</label>
                                </div>
                                <div class="center">
                                    <input type="text" name="seotitle" class="" placeholder="" value="{{$subcategory->seotitle or ''}}">
                                </div>
                                <div class="right">
                                    <div class="help"></div>
                                </div>
                            </div>
                            <div class="item_line">
                              <div class="left">
                                  <label for="" class="item_name">Мета-тег Description:</label>
                              </div>
                                <div class="center">
                                    <input type="text" name="seodescription" class="" placeholder="" value="{{$subcategory->seodescription or ''}}">
                                </div>
                                <div class="right">
                                    <div class="help"></div>
                                </div>
                            </div>
                            <div class="item_line">
                                <div class="left">
                                    <label for="" class="item_name">Мета-тег Keywords:</label>
                                </div>
                                <div class="center">
                                    <input type="text" name="seokeywords" class="" placeholder="" value="{{$subcategory->seokeywords or ''}}">
                                </div>
                                <div class="right">
                                    <div class="help"></div>
                                </div>
                            </div>
                        </div>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="item_name">Название категории:</label>
                            </div>
                            <div class="center">
                                <input type="text" name="title" class="" placeholder="Введите название категории" value="{{$subcategory->title or ''}}" required="">
                            </div>
                            <div class="right">
                                <div class="help"></div>
                            </div>
                        </div>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="item_name">Оффер категории:</label>
                            </div>
                            <div class="center">
                                <input type="text" name="offer" class="" placeholder="Введите оффер категории" value="{{$subcategory->offer or ''}}" required="">
                            </div>
                            <div class="right">
                                <div class="help"></div>
                            </div>
                        </div>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="item_name" style="line-height: 14px;">Описание категории:</label>
                            </div>
                            <div class="center">
                                <textarea rows="10" name="text">{{$subcategory->description or ''}}</textarea>
                            </div>
                        </div>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="item_name" style="line-height: 14px;">Фотография:</label>
                            </div>
                            <div class="center">
                                <div class="file-upload">
                                    <label>
                                        <input type="file" name="file">
                                        <span>Выбрать файл</span>
                                    </label>
                                </div>
                                <input type="text" id="filename" class="filename" disabled style="border: none;font-size: 12px;">
                                @if($subcategory !== null)
                                @if($subcategory->images !== null)
                                <div class="image_group" id="image{{$subcategory->id}}">
                                    <div class="image">
                                        <img src="{{asset('storage/app')}}/{{$subcategory->images->images or ''}}" alt="">
                                        <a  class="delete" id="send"></a>
                                    </div>
                                </div>

                                <script>

                                ajaxForm();
                                function ajaxForm(){
                                  $('#send').click(function(){
                                    var data = new FormData($("#form")[0]);
                                      $.ajax({
                                          type: 'GET',
                                          url: "{{route('admin.image.subcategory.destroy')}}?id={{$subcategory->images->id}}",
                                          data: data,
                                          headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') },
                                          contentType: false,
                                          processData : false,
                                          success: function(data) {
                                              $('#image{{$subcategory->id}}').html('');
                                          }
                                      });
                                      return false;
                                  });
                                }

                        </script>
                                @endif
                                @endif
                            </div>
                        </div>
                        <div class="perent">
                            <div class="left">
                                <label for="" class="item_name">Видео с YouTube:</label>
                            </div>
                            <div class="center">
                                <input type="text" name="youtube" class="" placeholder="Например: http://www.youtube.com/watch?v=9X-8JiOhzX4" value="{{$subcategory->youtube or ''}}">
                            </div>
                            <div class="right">
                                <div class="help"></div>
                            </div>
                        </div>
                        <div class="perent" style="margin-top: 40px;">
                            <div class="left">&nbsp</div>
                            <div class="center">
                              @if($subcategory !== null)
                              <input type="submit" class="item_button" value="Обновить">
                              @else
                              <input type="submit" class="item_button" value="Добавить">
                              @endif
                            </div>
                            <div class="right"></div>
                        </div>
                      </form>
                    </div>
                </div>



            </div>
        </div>
        <script>
            $(document).ready(function () {
                $(".file-upload input[type=file]").change(function () {
                    var filename = $(this).val().replace(/.*\\/, "");
                    $("#filename").val(filename);
                });
            });
        </script>
        <script>
            $(document).ready(function () {
                $('input[type="checkbox"]').click(function () {
                    if ($(this).attr('id') == 'watch') {
                        if (this.checked) {
                            $('#switch_seo').show();
                        } else {
                            $('#switch_seo').hide();
                        }
                    }
                });
            });
        </script>
        @if($subcategory !== null)
            @if($subcategory->checkseo == 1)
                <script>
                    $(document).ready(function () {
                        $('#switch_seo').show();
                    });
                </script>
            @endif
        @endif
    </div>
</div>